import type { InspectionItem } from '../types';

export const INSPECTION_ITEMS: InspectionItem[] = [
  {
    id: 'item-001',
    name: '墙面垂直度',
    category: '墙面工程',
    designValue: 0,
    allowablePositiveDeviation: 3,
    allowableNegativeDeviation: 3,
    unit: 'mm',
    standardCode: 'GB50210-2018',
    requirePhoto: true,
  },
  {
    id: 'item-002',
    name: '墙面平整度',
    category: '墙面工程',
    designValue: 0,
    allowablePositiveDeviation: 3,
    allowableNegativeDeviation: 3,
    unit: 'mm',
    standardCode: 'GB50210-2018',
    requirePhoto: true,
  },
  {
    id: 'item-003',
    name: '地面平整度',
    category: '地面工程',
    designValue: 0,
    allowablePositiveDeviation: 4,
    allowableNegativeDeviation: 4,
    unit: 'mm',
    standardCode: 'GB50209-2010',
    requirePhoto: true,
  },
  {
    id: 'item-004',
    name: '地面水平度',
    category: '地面工程',
    designValue: 0,
    allowablePositiveDeviation: 5,
    allowableNegativeDeviation: 5,
    unit: 'mm',
    standardCode: 'GB50209-2010',
    requirePhoto: false,
  },
  {
    id: 'item-005',
    name: '顶棚水平度',
    category: '顶棚工程',
    designValue: 0,
    allowablePositiveDeviation: 5,
    allowableNegativeDeviation: 5,
    unit: 'mm',
    standardCode: 'GB50210-2018',
    requirePhoto: false,
  },
  {
    id: 'item-006',
    name: '顶棚平整度',
    category: '顶棚工程',
    designValue: 0,
    allowablePositiveDeviation: 3,
    allowableNegativeDeviation: 3,
    unit: 'mm',
    standardCode: 'GB50210-2018',
    requirePhoto: true,
  },
  {
    id: 'item-007',
    name: '门窗洞口宽度',
    category: '门窗工程',
    designValue: 900,
    allowablePositiveDeviation: 10,
    allowableNegativeDeviation: 10,
    unit: 'mm',
    standardCode: 'GB50210-2018',
    requirePhoto: true,
  },
  {
    id: 'item-008',
    name: '门窗洞口高度',
    category: '门窗工程',
    designValue: 2100,
    allowablePositiveDeviation: 10,
    allowableNegativeDeviation: 10,
    unit: 'mm',
    standardCode: 'GB50210-2018',
    requirePhoto: true,
  },
  {
    id: 'item-009',
    name: '门窗对角线',
    category: '门窗工程',
    designValue: 0,
    allowablePositiveDeviation: 5,
    allowableNegativeDeviation: 5,
    unit: 'mm',
    standardCode: 'GB50210-2018',
    requirePhoto: false,
  },
  {
    id: 'item-010',
    name: '开间净尺寸',
    category: '空间尺寸',
    designValue: 3600,
    allowablePositiveDeviation: 15,
    allowableNegativeDeviation: 15,
    unit: 'mm',
    standardCode: 'JGJ/T304-2013',
    requirePhoto: true,
  },
  {
    id: 'item-011',
    name: '进深净尺寸',
    category: '空间尺寸',
    designValue: 4200,
    allowablePositiveDeviation: 15,
    allowableNegativeDeviation: 15,
    unit: 'mm',
    standardCode: 'JGJ/T304-2013',
    requirePhoto: true,
  },
  {
    id: 'item-012',
    name: '层高净空',
    category: '空间尺寸',
    designValue: 2800,
    allowablePositiveDeviation: 20,
    allowableNegativeDeviation: 20,
    unit: 'mm',
    standardCode: 'JGJ/T304-2013',
    requirePhoto: true,
  },
  {
    id: 'item-013',
    name: '阴阳角方正',
    category: '细部工程',
    designValue: 90,
    allowablePositiveDeviation: 3,
    allowableNegativeDeviation: 3,
    unit: '度',
    standardCode: 'GB50210-2018',
    requirePhoto: true,
  },
  {
    id: 'item-014',
    name: '踢脚线垂直度',
    category: '细部工程',
    designValue: 0,
    allowablePositiveDeviation: 2,
    allowableNegativeDeviation: 2,
    unit: 'mm',
    standardCode: 'GB50210-2018',
    requirePhoto: false,
  },
  {
    id: 'item-015',
    name: '墙砖空鼓率',
    category: '墙面工程',
    designValue: 0,
    allowablePositiveDeviation: 5,
    allowableNegativeDeviation: 0,
    unit: '%',
    standardCode: 'GB50210-2018',
    requirePhoto: true,
  },
  {
    id: 'item-016',
    name: '地砖空鼓率',
    category: '地面工程',
    designValue: 0,
    allowablePositiveDeviation: 5,
    allowableNegativeDeviation: 0,
    unit: '%',
    standardCode: 'GB50209-2010',
    requirePhoto: true,
  },
];

export const INSPECTION_CATEGORIES = [
  '墙面工程',
  '地面工程',
  '顶棚工程',
  '门窗工程',
  '空间尺寸',
  '细部工程',
];

export const DEFAULT_INSPECTION_ITEM_MAP: Record<string, InspectionItem> =
  INSPECTION_ITEMS.reduce((acc, item) => {
    acc[item.name] = item;
    return acc;
  }, {} as Record<string, InspectionItem>);
